version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-container
    ports:
      - "${PHP_PORT}:80"
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - app-network

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap-server
    environment:
      LDAP_ORGANISATION: "${LDAP_ORGANISATION}"
      LDAP_DOMAIN: "${LDAP_DOMAIN}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASSWORD}"
    ports:
      - "${LDAP_PORT}:389"
      - "${LDAP_SECURE_PORT}:636"
    volumes:
      - ${LDAP_DATA_VOLUME}:/var/lib/ldap
      - ${LDAP_CONFIG_VOLUME}:/etc/ldap/slapd.d
    networks:
      - app-network

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-server
    ports:
      - "${PHPLDAPADMIN_PORT}:443"
    networks:
      - app-network
    depends_on:
      - ldap

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  mysql-data:
  ldap-data:
  ldap-config:
